/**************************************************************************************************\
 *** 
 *** Simulink model       : LostComnFaltBus_1_TL
 *** TargetLink subsystem : LostComnFaltBus_1_TL/LostComnFaltBus_1_TL/Subsystem/LostComnFaltBus_1_TL
 ***                        /LostComnFaltBus
 *** Codefile             : lostcomnfaltbus_cal.h
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2018-10-09 17:34:34
 ***
 *** CODE GENERATOR OPTIONS:
 *** Compiler                            : <unknown>
 *** Target                              : Generic
 *** ANSI-C compatible code              : yes
 *** Optimization level                  : 2
 *** Constant style                      : decimal
 *** Clean code option                   : enabled
 *** Logging mode                        : Do not log anything
 *** Linker sections                     : enabled
 *** Assembler statements                : disabled
 *** Variable name length                : 31 chars
 *** Use global bitfields                : disabled
 *** Stateflow: use of bitfields         : enabled
 *** State activity encoding limit       : 5
 *** Omit zero inits in restart function : enabled
 *** Share fcns between TL subsystems    : disabled
 *** Generate 64bit functions            : disabled
 *** Inlining Threshold                  : 6
 *** Line break limit                    : 100
 *** Target optimized boolean data type  : enabled
 *** Keep saturation elements            : disabled
 *** Extended variable sharing           : disabled
 *** Style definition file               : C:\56748_Release 2013A\Matlab\Tl\config\codegen\cconfig.x
 ***                                       ml
 *** Root style sheet                    : C:\56748_Release 2013A\Matlab\Tl\XML\CodeGen\Stylesheets\
 ***                                       TL_CSourceCodeSS.xsl
 *** Enable Multirate codegeneration     : disabled
 *** Add model checksum                  : disabled
 ***
 *** TargetLink version      : 2.3 from 05-Mar-2008
 *** Code generator version  : Build Id 2.3.0.17 from 2008-02-07 15:20:42
 *** Copyright (c) 2006 dSPACE GmbH
\**************************************************************************************************/

#ifndef _LOSTCOMNFALTBUS_CAL_H_
#define _LOSTCOMNFALTBUS_CAL_H_

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/
#include "tl_defines_LostComnFB.h"
#include "tl_basetypes.h"
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/

/******************************************************************************\
   CAL: global calibratable parameters (ROM) | Width: 16
\******************************************************************************/
extern CAL U16 C_FaultTimeTrBO /* LSB: 0.1 OFF:  0 MIN/MAX:  0 .. 6553.5 */;
extern CAL U16 C_FaultTimeTrCH /* LSB: 0.1 OFF:  0 MIN/MAX:  0 .. 6553.5 */;
extern CAL U16 C_FaultTimeTrCO /* LSB: 0.1 OFF:  0 MIN/MAX:  0 .. 6553.5 */;
extern CAL U16 C_FaultTimeTrFR /* LSB: 0.1 OFF:  0 MIN/MAX:  0 .. 6553.5 */;
extern CAL U16 C_FaultTimeTrHY /* LSB: 0.1 OFF:  0 MIN/MAX:  0 .. 6553.5 */;
extern CAL U16 C_FaultTimeTrPMZ /* LSB: 0.1 OFF:  0 MIN/MAX:  0 .. 6553.5 */;
extern CAL U16 C_FaultTimeTrPT /* LSB: 0.1 OFF:  0 MIN/MAX:  0 .. 6553.5 */;

/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/

#endif/*_LOSTCOMNFALTBUS_CAL_H_ */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
