/**************************************************************************************************\
 *** 
 *** Simulink model       : VscAtic_Params_TL
 *** TargetLink subsystem : VscAtic_Params_TL/VscAtic_Params_TL/Subsystem/VscAtic_Params_TL/VscAtic_
 ***                        Params
 *** Codefile             : vscatic_params_cal.h
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2020-12-17 19:38:14
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Standard
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Variable vector widths                   : enabled
 *** Shift mode                               : automatic
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : enabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : disabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 4.1\Matlab\TL\con
 ***                                            fig\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 4.1\Matlab\TL\XML
 ***                                            \CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** TargetLink version      : 4.1 from 12-Oct-2015
 *** Code generator version  : Build Id 4.1.0.21 from 2015-09-25 11:04:18

\**************************************************************************************************/

#ifndef VSCATIC_PARAMS_CAL_H
#define VSCATIC_PARAMS_CAL_H

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/
#include "tl_defines_VAticParam.h"
#include "tl_basetypes.h"
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/

/******************************************************************************\
   CAL: global calibratable parameters (ROM) | Width: 16
\******************************************************************************/
extern CAL U16 CdiffLockTq7FaltStateLim_Tq_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;
extern CAL U16 CdiffLockTq7State1InitLim_Tq_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;
extern CAL U16 CdiffLockTq7State1Lim_Tq_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;
extern CAL U16 CdiffLockTq7State2InitLim_Tq_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;
extern CAL U16 CdiffLockTq7State2Lim_Tq_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;
extern CAL U16 CdiffLockTq7State3InitLim_Tq_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;
extern CAL U16 CdiffLockTq7State3Lim_Tq_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;
extern CAL U16 CdiffLockTqFaltStateLim_Tq_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;
extern CAL U16 CdiffLockTqState1InitLim_Tq_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;
extern CAL U16 CdiffLockTqState1Lim_Tq_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;
extern CAL U16 CdiffLockTqState2InitLim_Tq_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;
extern CAL U16 CdiffLockTqState2Lim_Tq_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;
extern CAL U16 CdiffLockTqState3InitLim_Tq_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;
extern CAL U16 CdiffLockTqState3Lim_Tq_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;
extern CAL U16 CdiffTq7JagFaltStateLimDfalt_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;
extern CAL U16 CdiffTq7JagFaltStateLimWntr_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;
extern CAL U16 CdiffTq7State3LimDfalt_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;
extern CAL U16 CdiffTq7State4LimDfalt_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;
extern CAL U16 CdiffTq7State4LimWntr_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;
extern CAL U16 EleMtrTqFrntReqHmi_Tq_Max_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;
extern CAL U16 EleMtrTqRearReqHmi_Tq_Max_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;
extern CAL U16 RdiffLockTqFaltStateLim_Tq_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;
extern CAL U16 RdiffLockTqState1InitLim_Tq_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;
extern CAL U16 RdiffLockTqState1Lim_Tq_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;
extern CAL U16 RdiffLockTqState2InitLim_Tq_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;
extern CAL U16 RdiffLockTqState2Lim_Tq_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;
extern CAL U16 RdiffLockTqState3InitLim_Tq_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;
extern CAL U16 RdiffLockTqState3Lim_Tq_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;

/******************************************************************************\
   CAL: global calibratable parameters (ROM) | Width: 8
\******************************************************************************/
extern CAL U8 CdiffLockTq7FaltState_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 CdiffLockTq7JagFaltState_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 CdiffLockTq7JagState0_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 CdiffLockTq7JagState1_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 CdiffLockTq7JagState2_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 CdiffLockTq7JagState3_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 CdiffLockTq7JagState4_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 CdiffLockTq7State0_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 CdiffLockTq7State1_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 CdiffLockTq7State2_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 CdiffLockTq7State3_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 CdiffLockTqFaltState_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 CdiffLockTqState0_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 CdiffLockTqState1_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 CdiffLockTqState2_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 CdiffLockTqState3_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 CdiffTq7State1LimDfalt_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 CdiffTq7State1LimWntr_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 CdiffTq7State2LimDfalt_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 CdiffTq7State2LimWntr_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 CdiffTq7State3LimWntr_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 CntrCluTqFaltStateLim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 CntrCluTqFaltState_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 CntrCluTqState0_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 CntrCluTqState1InitLim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 CntrCluTqState1Lim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 CntrCluTqState1_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 CntrCluTqState2InitLim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 CntrCluTqState2Lim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 CntrCluTqState2_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 CntrCluTqState3InitLim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 CntrCluTqState3Lim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 CntrCluTqState3_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 CntrCluTqState4InitLim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 CntrCluTqState4Lim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 CntrCluTqState4_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 CntrCluTqState5InitLim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 CntrCluTqState5Lim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 CntrCluTqState5_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 EleMtrTqHmiState0_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 EleMtrTqHmiState1InitLim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 EleMtrTqHmiState1Lim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 EleMtrTqHmiState1_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 EleMtrTqHmiState2InitLim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 EleMtrTqHmiState2Lim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 EleMtrTqHmiState2_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 EleMtrTqHmiState3InitLim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 EleMtrTqHmiState3Lim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 EleMtrTqHmiState3_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 EleMtrTqHmiState4InitLim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 EleMtrTqHmiState4Lim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 EleMtrTqHmiState4_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 EleMtrTqHmiState5InitLim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 EleMtrTqHmiState5Lim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 EleMtrTqHmiState5_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 FaTqFaltStateLim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 FaTqFaltState_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 FaTqState0_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 FaTqState1InitLim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 FaTqState1Lim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 FaTqState1_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 FaTqState2InitLim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 FaTqState2Lim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 FaTqState2_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 FaTqState3InitLim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 FaTqState3Lim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 FaTqState3_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 FaTqState4InitLim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 FaTqState4Lim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 FaTqState4_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 FaTqState5InitLim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 FaTqState5Lim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 FaTqState5_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 RdiffLockTqFaltState_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 RdiffLockTqState0_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 RdiffLockTqState1_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 RdiffLockTqState2_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 RdiffLockTqState3_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 RlCluTqFaltStateLim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 RlCluTqFaltState_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 RlCluTqState0_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 RlCluTqState1InitLim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 RlCluTqState1Lim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 RlCluTqState1_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 RlCluTqState2InitLim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 RlCluTqState2Lim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 RlCluTqState2_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 RlCluTqState3InitLim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 RlCluTqState3Lim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 RlCluTqState3_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 RlCluTqState4InitLim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 RlCluTqState4Lim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 RlCluTqState4_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 RlCluTqState5InitLim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 RlCluTqState5Lim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 RlCluTqState5_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 RrCluTqFaltStateLim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 RrCluTqFaltState_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 RrCluTqState0_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 RrCluTqState1InitLim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 RrCluTqState1Lim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 RrCluTqState1_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 RrCluTqState2InitLim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 RrCluTqState2Lim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 RrCluTqState2_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 RrCluTqState3InitLim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 RrCluTqState3Lim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 RrCluTqState3_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 RrCluTqState4InitLim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 RrCluTqState4Lim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 RrCluTqState4_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 RrCluTqState5InitLim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 RrCluTqState5Lim_Pc_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern CAL U8 RrCluTqState5_Zs_Pt /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;

/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/

#endif /* VSCATIC_PARAMS_CAL_H */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
