/**************************************************************************************************\
 *** 
 *** Simulink model       : FaltDBGLogic_1_TL
 *** TargetLink subsystem : FaltDBGLogic_1_TL/FaltDBGLogic_1_TL/Subsystem/FaltDBGLogic_1_TL/FaltDBGL
 ***                        ogic
 *** Codefile             : faltdbglogic_cal.c
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2019-04-12 15:06:20
 ***
 *** CODE GENERATOR OPTIONS:
 *** Compiler                            : <unknown>
 *** Target                              : Generic
 *** ANSI-C compatible code              : yes
 *** Optimization level                  : 2
 *** Constant style                      : decimal
 *** Clean code option                   : enabled
 *** Logging mode                        : Do not log anything
 *** Linker sections                     : enabled
 *** Assembler statements                : disabled
 *** Variable name length                : 31 chars
 *** Use global bitfields                : disabled
 *** Stateflow: use of bitfields         : enabled
 *** State activity encoding limit       : 5
 *** Omit zero inits in restart function : enabled
 *** Share fcns between TL subsystems    : disabled
 *** Generate 64bit functions            : disabled
 *** Inlining Threshold                  : 6
 *** Line break limit                    : 100
 *** Target optimized boolean data type  : enabled
 *** Keep saturation elements            : disabled
 *** Extended variable sharing           : disabled
 *** Style definition file               : C:\56748_Release 2013A\Matlab\Tl\config\codegen\cconfig.x
 ***                                       ml
 *** Root style sheet                    : C:\56748_Release 2013A\Matlab\Tl\XML\CodeGen\Stylesheets\
 ***                                       TL_CSourceCodeSS.xsl
 *** Enable Multirate codegeneration     : disabled
 *** Add model checksum                  : disabled
 ***
 *** SUBSYS                   CORRESPONDING SIMULINK SUBSYSTEM
 *** SFaltDBGLog1             FaltDBGLogic_1_TL/FaltDBGLogic
 *** SFaltDBGLog2             FaltDBGLogic/Bitwise LogicalOperator1
 *** SFaltDBGLog3             FaltDBGLogic/Bitwise LogicalOperator2
 *** SFaltDBGLog4             FaltDBGLogic/Bitwise LogicalOperator3
 *** SFaltDBGLog5             FaltDBGLogic/Bitwise LogicalOperator4
 *** SFaltDBGLog6             FaltDBGLogic/FaltLogLogic
 *** SFaltDBGLog7             FaltDBGLogic/Subsystem
 *** SFaltDBGLog8             FaltDBGLogic/Subsystem2
 *** SFaltDBGLog9             FaltDBGLogic/FaltLogLogic/Subsystem
 *** SFaltDBGLog10            FaltDBGLogic/FaltLogLogic/Subsystem2
 *** 
 *** SF-NODE   CORRESPONDING STATEFLOW NODE                           DESCRIPTION
 *** CFaltDBGL
 *** og0       FaltDBGLogic_1_TL                                      
 *** CFaltDBGL
 *** og1       FaltDBGLogic/FaltLogLogic/FaltLogLogic                 
 *** CFaltDBGL
 *** og2       FaltDBGLogic/FaltLogLogic/FaltLogLogic.Faltchecking    
 *** 
 *** TargetLink version      : 2.3 from 05-Mar-2008
 *** Code generator version  : Build Id 2.3.0.17 from 2008-02-07 15:20:42
 *** Copyright (c) 2006 dSPACE GmbH
\**************************************************************************************************/

#ifndef _FALTDBGLOGIC_CAL_C_
#define _FALTDBGLOGIC_CAL_C_

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/
#include "faltdbglogic_cal.h"
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/

#pragma section const_type ".FLASH_CAL_DATA" ".FLASH_CAL_DATA"
/******************************************************************************\
   CAL: global calibratable parameters (ROM) | Width: 32
\******************************************************************************/

__declspec (section ".FLASH_CAL_DATA") 
CAL U32 DTC_Req_Pt[4] = 
{
   /*[0..3]*/ 2549661630U, 2205241261U, 4092743665U, 1
   /* 2549661630.U, 2205241261.U, 4092743665.U, 1. */
} /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 4294967295 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U32 MaskWord_BO_Pt[4] = 
{
   /*[0..3]*/ 2147483648U, 63, 0, 0
   /* 2147483648.U, 63., 0., 0. */
} /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 4294967295 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U32 MaskWord_CH_Pt[4] = 
{
   /*[0..3]*/ 1610612736, 0, 4089597696U, 0
   /* 1610612736., 0., 4089597696.U, 0. */
} /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 4294967295 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U32 MaskWord_CO_Pt[4] = 
{
   /*[0..3]*/ 0, 64, 0, 1
   /* 0., 64., 0., 1. */
} /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 4294967295 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U32 MaskWord_FR_Pt[4] = 
{
   /*[0..3]*/ 0, 4294934528U, 3145983, 0
   /* 0., 4294934528.U, 3145983., 0. */
} /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 4294967295 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U32 MaskWord_HY_Pt[4] = 
{
   /*[0..3]*/ 0, 0, 0, 0
   /* 0., 0., 0., 0. */
} /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 4294967295 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U32 MaskWord_PMZ_Pt[4] = 
{
   /*[0..3]*/ 536870910, 0, 0, 0
   /* 536870910., 0., 0., 0. */
} /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 4294967295 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U32 MaskWord_PT_Pt[4] = 
{
   /*[0..3]*/ 1, 17280, 0, 0
   /* 1., 17280., 0., 0. */
} /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 4294967295 */;

/******************************************************************************\
   CAL: global calibratable parameters (ROM) | Width: 16
\******************************************************************************/

__declspec (section ".FLASH_CAL_DATA") 
CAL U16 SscGTwmSigIDAry_Z_Pt[128] = 
{
   /*[0..9]*/ 793, 390, 462, 463, 464, 465, 525, 543, 544, 557, 
   /*[10..19]*/ 673, 3313, 700, 708, 710, 713, 775, 828, 904, 993, 
   /*[20..29]*/ 994, 1950, 973, 974, 1064, 1079, 1736, 2313, 2039, 791, 
   /*[30..39]*/ 3759, 294, 455, 1879, 2421, 2009, 2011, 1371, 1936, 2815, 
   /*[40..49]*/ 2624, 2625, 2619, 2622, 2620, 2621, 2471, 2321, 327, 3705, 
   /*[50..59]*/ 481, 567, 2091, 628, 630, 634, 637, 644, 671, 3617, 
   /*[60..69]*/ 3618, 122, 2775, 815, 1019, 975, 3670, 3671, 186, 1224, 
   /*[70..79]*/ 1066, 409, 4035, 38, 443, 219, 2074, 290, 4681, 215, 
   /*[80..89]*/ 2306, 216, 1180, 1177, 3842, 3819, 3696, 3790, 3693, 3876, 
   /*[90..99]*/ 8096, 3873, 618, 218, 217, 3881, 2254, 0, 0, 0, 
   /*[100..109]*/ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
   /*[110..119]*/ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
   /*[120..127]*/ 0, 0, 0, 0, 0, 0, 0, 0
   /* 793., 390., 462., 463., 464., 465., 525., 543., 544., 557., 
   673., 3313., 700., 708., 710., 713., 775., 828., 904., 993., 
   994., 1950., 973., 974., 1064., 1079., 1736., 2313., 2039., 791., 
   3759., 294., 455., 1879., 2421., 2009., 2011., 1371., 1936., 2815., 
   2624., 2625., 2619., 2622., 2620., 2621., 2471., 2321., 327., 3705., 
   481., 567., 2091., 628., 630., 634., 637., 644., 671., 3617., 
   3618., 122., 2775., 815., 1019., 975., 3670., 3671., 186., 1224., 
   1066., 409., 4035., 38., 443., 219., 2074., 290., 4681., 215., 
   2306., 216., 1180., 1177., 3842., 3819., 3696., 3790., 3693., 3876., 
   8096., 3873., 618., 218., 217., 3881., 2254., 0., 0., 0., 
   0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 
   0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 
   0., 0., 0., 0., 0., 0., 0., 0. */
} /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;

/******************************************************************************\
   CAL: global calibratable parameters (ROM) | Width: 8
\******************************************************************************/

__declspec (section ".FLASH_CAL_DATA") 
CAL Bool EnblSigDbgLogic_B = 1 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;

#pragma section ".default"

/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INLINE FUNCTIONS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/

#endif/*_FALTDBGLOGIC_CAL_C_ */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
