/**************************************************************************************************\
 *** 
 *** Simulink model       : InvalidMsgFalt_1_TL
 *** TargetLink subsystem : InvalidMsgFalt_1_TL/InvalidMsgFalt_1_TL/Subsystem/InvalidMsgFalt_1_TL/In
 ***                        validMsgFalt
 *** Codefile             : invalidmsgfalt_cal.c
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2019-04-12 14:02:38
 ***
 *** CODE GENERATOR OPTIONS:
 *** Compiler                            : <unknown>
 *** Target                              : Generic
 *** ANSI-C compatible code              : yes
 *** Optimization level                  : 2
 *** Constant style                      : decimal
 *** Clean code option                   : enabled
 *** Logging mode                        : Do not log anything
 *** Linker sections                     : enabled
 *** Assembler statements                : disabled
 *** Variable name length                : 31 chars
 *** Use global bitfields                : disabled
 *** Stateflow: use of bitfields         : enabled
 *** State activity encoding limit       : 5
 *** Omit zero inits in restart function : enabled
 *** Share fcns between TL subsystems    : disabled
 *** Generate 64bit functions            : disabled
 *** Inlining Threshold                  : 6
 *** Line break limit                    : 100
 *** Target optimized boolean data type  : enabled
 *** Keep saturation elements            : disabled
 *** Extended variable sharing           : disabled
 *** Style definition file               : C:\56748_Release 2013A\Matlab\Tl\config\codegen\cconfig.x
 ***                                       ml
 *** Root style sheet                    : C:\56748_Release 2013A\Matlab\Tl\XML\CodeGen\Stylesheets\
 ***                                       TL_CSourceCodeSS.xsl
 *** Enable Multirate codegeneration     : disabled
 *** Add model checksum                  : disabled
 ***
 *** SUBSYS                   CORRESPONDING SIMULINK SUBSYSTEM
 *** SInvalidMsg1             InvalidMsgFalt_1_TL/InvalidMsgFalt
 *** SInvalidMsg2             InvalidMsgFalt/InvalidMsgFalt_check
 *** SInvalidMsg3             InvalidMsgFalt/InvalidMsgFalt_check/Bitwise LogicalOperator1
 *** SInvalidMsg4             InvalidMsgFalt/InvalidMsgFalt_check/Bitwise LogicalOperator10
 *** SInvalidMsg5             InvalidMsgFalt/InvalidMsgFalt_check/Bitwise LogicalOperator11
 *** SInvalidMsg6             InvalidMsgFalt/InvalidMsgFalt_check/Bitwise LogicalOperator12
 *** SInvalidMsg7             InvalidMsgFalt/InvalidMsgFalt_check/Bitwise LogicalOperator14
 *** SInvalidMsg8             InvalidMsgFalt/InvalidMsgFalt_check/Bitwise LogicalOperator16
 *** SInvalidMsg9             InvalidMsgFalt/InvalidMsgFalt_check/Bitwise LogicalOperator2
 *** SInvalidMsg10            InvalidMsgFalt/InvalidMsgFalt_check/Bitwise LogicalOperator3
 *** SInvalidMsg11            InvalidMsgFalt/InvalidMsgFalt_check/Bitwise LogicalOperator4
 *** SInvalidMsg12            InvalidMsgFalt/InvalidMsgFalt_check/Bitwise LogicalOperator7
 *** SInvalidMsg13            InvalidMsgFalt/InvalidMsgFalt_check/Bitwise LogicalOperator8
 *** SInvalidMsg14            InvalidMsgFalt/InvalidMsgFalt_check/Bitwise LogicalOperator9
 *** SInvalidMsg15            InvalidMsgFalt/InvalidMsgFalt_check/FaltWordPack_Invalid
 *** SInvalidMsg16            InvalidMsgFalt/InvalidMsgFalt_check/Subsystem1
 *** SInvalidMsg17            InvalidMsgFalt/InvalidMsgFalt_check/Subsystem16
 *** SInvalidMsg18            InvalidMsgFalt/InvalidMsgFalt_check/Subsystem2
 *** SInvalidMsg19            InvalidMsgFalt/InvalidMsgFalt_check/Subsystem20
 *** SInvalidMsg20            InvalidMsgFalt/InvalidMsgFalt_check/Subsystem3
 *** SInvalidMsg21            InvalidMsgFalt/InvalidMsgFalt_check/Subsystem4
 *** SInvalidMsg22            InvalidMsgFalt/InvalidMsgFalt_check/Subsystem5
 *** SInvalidMsg23            InvalidMsgFalt/InvalidMsgFalt_check/Subsystem6
 *** SInvalidMsg24            InvalidMsgFalt/InvalidMsgFalt_check/Subsystem7
 *** SInvalidMsg25            InvalidMsgFalt/InvalidMsgFalt_check/Subsystem8
 *** SInvalidMsg26            InvalidMsgFalt/InvalidMsgFalt_check/FaltWordPack_Invalid/BitwiseLogica
 ***                          l Operator1
 *** SInvalidMsg27            InvalidMsgFalt/InvalidMsgFalt_check/FaltWordPack_Invalid/BitwiseLogica
 ***                          l Operator10
 *** SInvalidMsg28            InvalidMsgFalt/InvalidMsgFalt_check/FaltWordPack_Invalid/BitwiseLogica
 ***                          l Operator11
 *** SInvalidMsg29            InvalidMsgFalt/InvalidMsgFalt_check/FaltWordPack_Invalid/BitwiseLogica
 ***                          l Operator12
 *** SInvalidMsg30            InvalidMsgFalt/InvalidMsgFalt_check/FaltWordPack_Invalid/BitwiseLogica
 ***                          l Operator13
 *** SInvalidMsg31            InvalidMsgFalt/InvalidMsgFalt_check/FaltWordPack_Invalid/BitwiseLogica
 ***                          l Operator14
 *** SInvalidMsg32            InvalidMsgFalt/InvalidMsgFalt_check/FaltWordPack_Invalid/BitwiseLogica
 ***                          l Operator15
 *** SInvalidMsg33            InvalidMsgFalt/InvalidMsgFalt_check/FaltWordPack_Invalid/BitwiseLogica
 ***                          l Operator16
 *** SInvalidMsg34            InvalidMsgFalt/InvalidMsgFalt_check/FaltWordPack_Invalid/BitwiseLogica
 ***                          l Operator17
 *** SInvalidMsg35            InvalidMsgFalt/InvalidMsgFalt_check/FaltWordPack_Invalid/BitwiseLogica
 ***                          l Operator18
 *** SInvalidMsg36            InvalidMsgFalt/InvalidMsgFalt_check/FaltWordPack_Invalid/BitwiseLogica
 ***                          l Operator19
 *** SInvalidMsg37            InvalidMsgFalt/InvalidMsgFalt_check/FaltWordPack_Invalid/BitwiseLogica
 ***                          l Operator2
 *** SInvalidMsg38            InvalidMsgFalt/InvalidMsgFalt_check/FaltWordPack_Invalid/BitwiseLogica
 ***                          l Operator20
 *** SInvalidMsg39            InvalidMsgFalt/InvalidMsgFalt_check/FaltWordPack_Invalid/BitwiseLogica
 ***                          l Operator21
 *** SInvalidMsg40            InvalidMsgFalt/InvalidMsgFalt_check/FaltWordPack_Invalid/BitwiseLogica
 ***                          l Operator22
 *** SInvalidMsg41            InvalidMsgFalt/InvalidMsgFalt_check/FaltWordPack_Invalid/BitwiseLogica
 ***                          l Operator23
 *** SInvalidMsg42            InvalidMsgFalt/InvalidMsgFalt_check/FaltWordPack_Invalid/BitwiseLogica
 ***                          l Operator24
 *** SInvalidMsg43            InvalidMsgFalt/InvalidMsgFalt_check/FaltWordPack_Invalid/BitwiseLogica
 ***                          l Operator25
 *** SInvalidMsg44            InvalidMsgFalt/InvalidMsgFalt_check/FaltWordPack_Invalid/BitwiseLogica
 ***                          l Operator26
 *** SInvalidMsg45            InvalidMsgFalt/InvalidMsgFalt_check/FaltWordPack_Invalid/BitwiseLogica
 ***                          l Operator27
 *** SInvalidMsg46            InvalidMsgFalt/InvalidMsgFalt_check/FaltWordPack_Invalid/BitwiseLogica
 ***                          l Operator28
 *** SInvalidMsg47            InvalidMsgFalt/InvalidMsgFalt_check/FaltWordPack_Invalid/BitwiseLogica
 ***                          l Operator29
 *** SInvalidMsg48            InvalidMsgFalt/InvalidMsgFalt_check/FaltWordPack_Invalid/BitwiseLogica
 ***                          l Operator3
 *** SInvalidMsg49            InvalidMsgFalt/InvalidMsgFalt_check/FaltWordPack_Invalid/BitwiseLogica
 ***                          l Operator30
 *** SInvalidMsg50            InvalidMsgFalt/InvalidMsgFalt_check/FaltWordPack_Invalid/BitwiseLogica
 ***                          l Operator31
 *** SInvalidMsg51            InvalidMsgFalt/InvalidMsgFalt_check/FaltWordPack_Invalid/BitwiseLogica
 ***                          l Operator4
 *** SInvalidMsg52            InvalidMsgFalt/InvalidMsgFalt_check/FaltWordPack_Invalid/BitwiseLogica
 ***                          l Operator5
 *** SInvalidMsg53            InvalidMsgFalt/InvalidMsgFalt_check/FaltWordPack_Invalid/BitwiseLogica
 ***                          l Operator6
 *** SInvalidMsg54            InvalidMsgFalt/InvalidMsgFalt_check/FaltWordPack_Invalid/BitwiseLogica
 ***                          l Operator7
 *** SInvalidMsg55            InvalidMsgFalt/InvalidMsgFalt_check/FaltWordPack_Invalid/BitwiseLogica
 ***                          l Operator8
 *** SInvalidMsg56            InvalidMsgFalt/InvalidMsgFalt_check/FaltWordPack_Invalid/BitwiseLogica
 ***                          l Operator9
 *** 
 *** SF-NODE   CORRESPONDING STATEFLOW NODE                           DESCRIPTION
 *** CInvalidM
 *** sg0       InvalidMsgFalt_1_TL                                    
 *** CInvalidM
 *** sg1       InvalidMsgFalt/InvalidMsgFalt_check/FaltLogLogic_Inval
 ***           id                                                     
 *** 
 *** TargetLink version      : 2.3 from 05-Mar-2008
 *** Code generator version  : Build Id 2.3.0.17 from 2008-02-07 15:20:42
 *** Copyright (c) 2006 dSPACE GmbH
\**************************************************************************************************/

#ifndef _INVALIDMSGFALT_CAL_C_
#define _INVALIDMSGFALT_CAL_C_

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/
#include "invalidmsgfalt_cal.h"
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/

#pragma section const_type ".FLASH_CAL_DATA" ".FLASH_CAL_DATA"
/******************************************************************************\
   CAL: global calibratable parameters (ROM) | Width: 32
\******************************************************************************/

__declspec (section ".FLASH_CAL_DATA") 
CAL U32 DTC_Req_Invd_Pt[4] = 
{
   /*[0..3]*/ 1023, 0, 0, 0
   /* 1023., 0., 0., 0. */
} /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 4294967295 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U32 MaskWord_Invd_CH_Pt[4] = 
{
   /*[0..3]*/ 824, 0, 0, 0
   /* 824., 0., 0., 0. */
} /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 4294967295 */;

/******************************************************************************\
   CAL: global calibratable parameters (ROM) | Width: 16
\******************************************************************************/

__declspec (section ".FLASH_CAL_DATA") 
CAL U16 MaskWord_Invd_CO_Pt[4] = 
{
   /*[0..3]*/ 192, 0, 0, 0
   /* 192., 0., 0., 0. */
} /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U16 MaskWord_Invd_FR_Pt[4] = 
{
   /*[0..3]*/ 7, 0, 0, 0
   /* 7., 0., 0., 0. */
} /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U16 SscGTwmInvdSigIDAry_Zs[128] = 
{
   /*[0..9]*/ 3842, 3819, 9927, 3790, 3693, 3876, 9513, 14071, 1180, 1177, 
   /*[10..19]*/ 3696, 219, 8096, 3873, 215, 2306, 3881, 218, 217, 0, 
   /*[20..29]*/ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
   /*[30..39]*/ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
   /*[40..49]*/ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
   /*[50..59]*/ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
   /*[60..69]*/ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
   /*[70..79]*/ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
   /*[80..89]*/ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
   /*[90..99]*/ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
   /*[100..109]*/ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
   /*[110..119]*/ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
   /*[120..127]*/ 0, 0, 0, 0, 0, 0, 0, 0
   /* 3842., 3819., 9927., 3790., 3693., 3876., 9513., 14071., 1180., 1177., 
   3696., 219., 8096., 3873., 215., 2306., 3881., 218., 217., 0., 
   0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 
   0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 
   0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 
   0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 
   0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 
   0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 
   0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 
   0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 
   0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 
   0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 
   0., 0., 0., 0., 0., 0., 0., 0. */
} /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;

#pragma section ".default"

/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INLINE FUNCTIONS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/

#endif/*_INVALIDMSGFALT_CAL_C_ */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
