/**************************************************************************************************\
 *** 
 *** Simulink model       : LostComnFaltBus_1_TL
 *** TargetLink subsystem : LostComnFaltBus_1_TL/LostComnFaltBus_1_TL/Subsystem/LostComnFaltBus_1_TL
 ***                        /LostComnFaltBus
 *** Codefile             : lostcomnfaltbus_cal.c
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2018-10-09 17:34:34
 ***
 *** CODE GENERATOR OPTIONS:
 *** Compiler                            : <unknown>
 *** Target                              : Generic
 *** ANSI-C compatible code              : yes
 *** Optimization level                  : 2
 *** Constant style                      : decimal
 *** Clean code option                   : enabled
 *** Logging mode                        : Do not log anything
 *** Linker sections                     : enabled
 *** Assembler statements                : disabled
 *** Variable name length                : 31 chars
 *** Use global bitfields                : disabled
 *** Stateflow: use of bitfields         : enabled
 *** State activity encoding limit       : 5
 *** Omit zero inits in restart function : enabled
 *** Share fcns between TL subsystems    : disabled
 *** Generate 64bit functions            : disabled
 *** Inlining Threshold                  : 6
 *** Line break limit                    : 100
 *** Target optimized boolean data type  : enabled
 *** Keep saturation elements            : disabled
 *** Extended variable sharing           : disabled
 *** Style definition file               : C:\56748_Release 2013A\Matlab\Tl\config\codegen\cconfig.x
 ***                                       ml
 *** Root style sheet                    : C:\56748_Release 2013A\Matlab\Tl\XML\CodeGen\Stylesheets\
 ***                                       TL_CSourceCodeSS.xsl
 *** Enable Multirate codegeneration     : disabled
 *** Add model checksum                  : disabled
 ***
 *** SUBSYS                   CORRESPONDING SIMULINK SUBSYSTEM
 *** SLostComnFB1             LostComnFaltBus_1_TL/LostComnFaltBus
 *** SLostComnFB2             LostComnFaltBus/FaltBus
 *** SFaltDBGLog1             LostComnFaltBus/FaltDBGLogic
 *** SLostComnFB3             LostComnFaltBus/Subsystem1
 *** SLostComnFB4             LostComnFaltBus/Subsystem2
 *** SFaltFiltr1              LostComnFaltBus/FaltBus/FaltFiltr
 *** SFaltFiltr1              LostComnFaltBus/FaltBus/FaltFiltr1
 *** SFaltFiltr1              LostComnFaltBus/FaltBus/FaltFiltr2
 *** SFaltFiltr1              LostComnFaltBus/FaltBus/FaltFiltr3
 *** SFaltFiltr1              LostComnFaltBus/FaltBus/FaltFiltr4
 *** SFaltFiltr1              LostComnFaltBus/FaltBus/FaltFiltr5
 *** SFaltFiltr1              LostComnFaltBus/FaltBus/FaltFiltr6
 *** SFaltFiltr2              LostComnFaltBus/FaltBus/FaltFiltr/Subsystem
 *** SFaltFiltr3              LostComnFaltBus/FaltBus/FaltFiltr/Subsystem2
 *** SFaltFiltr2              LostComnFaltBus/FaltBus/FaltFiltr1/Subsystem
 *** SFaltFiltr3              LostComnFaltBus/FaltBus/FaltFiltr1/Subsystem2
 *** SFaltFiltr2              LostComnFaltBus/FaltBus/FaltFiltr2/Subsystem
 *** SFaltFiltr3              LostComnFaltBus/FaltBus/FaltFiltr2/Subsystem2
 *** SFaltFiltr2              LostComnFaltBus/FaltBus/FaltFiltr3/Subsystem
 *** SFaltFiltr3              LostComnFaltBus/FaltBus/FaltFiltr3/Subsystem2
 *** SFaltFiltr2              LostComnFaltBus/FaltBus/FaltFiltr4/Subsystem
 *** SFaltFiltr3              LostComnFaltBus/FaltBus/FaltFiltr4/Subsystem2
 *** SFaltFiltr2              LostComnFaltBus/FaltBus/FaltFiltr5/Subsystem
 *** SFaltFiltr3              LostComnFaltBus/FaltBus/FaltFiltr5/Subsystem2
 *** SFaltFiltr2              LostComnFaltBus/FaltBus/FaltFiltr6/Subsystem
 *** SFaltFiltr3              LostComnFaltBus/FaltBus/FaltFiltr6/Subsystem2
 *** SFaltDBGLog2             LostComnFaltBus/FaltDBGLogic/Bitwise LogicalOperator1
 *** SFaltDBGLog3             LostComnFaltBus/FaltDBGLogic/Bitwise LogicalOperator2
 *** SFaltDBGLog4             LostComnFaltBus/FaltDBGLogic/Bitwise LogicalOperator3
 *** SFaltDBGLog5             LostComnFaltBus/FaltDBGLogic/FaltLogLogic
 *** SFaltDBGLog6             LostComnFaltBus/FaltDBGLogic/Subsystem
 *** SFaltDBGLog7             LostComnFaltBus/FaltDBGLogic/Subsystem2
 *** SFaltDBGLog8             LostComnFaltBus/FaltDBGLogic/FaltLogLogic/Subsystem
 *** SFaltDBGLog9             LostComnFaltBus/FaltDBGLogic/FaltLogLogic/Subsystem2
 *** 
 *** SF-NODE   CORRESPONDING STATEFLOW NODE                           DESCRIPTION
 *** CLostComn
 *** FB0       FaltFiltr_1                                            
 *** CLostComn
 *** FB1       LostComnFaltBus_1_TL                                   
 *** CFaltFilt
 *** r1        LostComnFaltBus/FaltBus/FaltFiltr/FaltFiltrChrt        
 *** CFaltFilt
 *** r2        LostComnFaltBus/FaltBus/FaltFiltr/FaltFiltrChrt.Versio
 ***           nNumber                                                
 *** CFaltFilt
 *** r3        LostComnFaltBus/FaltBus/FaltFiltr/FaltFiltrChrt.FaltFi
 ***           ltr                                                    
 *** CFaltFilt
 *** r4        LostComnFaltBus/FaltBus/FaltFiltr/FaltFiltrChrt.FaltFi
 ***           ltr.FlagCleared                                        
 *** CFaltFilt
 *** r5        LostComnFaltBus/FaltBus/FaltFiltr/FaltFiltrChrt.FaltFi
 ***           ltr.DelayClearFlag                                     
 *** CFaltFilt
 *** r6        LostComnFaltBus/FaltBus/FaltFiltr/FaltFiltrChrt.FaltFi
 ***           ltr.DelaySetFlag                                       
 *** CFaltFilt
 *** r7        LostComnFaltBus/FaltBus/FaltFiltr/FaltFiltrChrt.FaltFi
 ***           ltr.FlagSet                                            
 *** CFaltFilt
 *** r1        LostComnFaltBus/FaltBus/FaltFiltr1/FaltFiltrChrt       
 *** CFaltFilt
 *** r2        LostComnFaltBus/FaltBus/FaltFiltr1/FaltFiltrChrt.Versi
 ***           onNumber                                               
 *** CFaltFilt
 *** r3        LostComnFaltBus/FaltBus/FaltFiltr1/FaltFiltrChrt.FaltF
 ***           iltr                                                   
 *** CFaltFilt
 *** r4        LostComnFaltBus/FaltBus/FaltFiltr1/FaltFiltrChrt.FaltF
 ***           iltr.FlagCleared                                       
 *** CFaltFilt
 *** r5        LostComnFaltBus/FaltBus/FaltFiltr1/FaltFiltrChrt.FaltF
 ***           iltr.DelayClearFlag                                    
 *** CFaltFilt
 *** r6        LostComnFaltBus/FaltBus/FaltFiltr1/FaltFiltrChrt.FaltF
 ***           iltr.DelaySetFlag                                      
 *** CFaltFilt
 *** r7        LostComnFaltBus/FaltBus/FaltFiltr1/FaltFiltrChrt.FaltF
 ***           iltr.FlagSet                                           
 *** CFaltFilt
 *** r1        LostComnFaltBus/FaltBus/FaltFiltr2/FaltFiltrChrt       
 *** CFaltFilt
 *** r2        LostComnFaltBus/FaltBus/FaltFiltr2/FaltFiltrChrt.Versi
 ***           onNumber                                               
 *** CFaltFilt
 *** r3        LostComnFaltBus/FaltBus/FaltFiltr2/FaltFiltrChrt.FaltF
 ***           iltr                                                   
 *** CFaltFilt
 *** r4        LostComnFaltBus/FaltBus/FaltFiltr2/FaltFiltrChrt.FaltF
 ***           iltr.FlagCleared                                       
 *** CFaltFilt
 *** r5        LostComnFaltBus/FaltBus/FaltFiltr2/FaltFiltrChrt.FaltF
 ***           iltr.DelayClearFlag                                    
 *** CFaltFilt
 *** r6        LostComnFaltBus/FaltBus/FaltFiltr2/FaltFiltrChrt.FaltF
 ***           iltr.DelaySetFlag                                      
 *** CFaltFilt
 *** r7        LostComnFaltBus/FaltBus/FaltFiltr2/FaltFiltrChrt.FaltF
 ***           iltr.FlagSet                                           
 *** CFaltFilt
 *** r1        LostComnFaltBus/FaltBus/FaltFiltr3/FaltFiltrChrt       
 *** CFaltFilt
 *** r2        LostComnFaltBus/FaltBus/FaltFiltr3/FaltFiltrChrt.Versi
 ***           onNumber                                               
 *** CFaltFilt
 *** r3        LostComnFaltBus/FaltBus/FaltFiltr3/FaltFiltrChrt.FaltF
 ***           iltr                                                   
 *** CFaltFilt
 *** r4        LostComnFaltBus/FaltBus/FaltFiltr3/FaltFiltrChrt.FaltF
 ***           iltr.FlagCleared                                       
 *** CFaltFilt
 *** r5        LostComnFaltBus/FaltBus/FaltFiltr3/FaltFiltrChrt.FaltF
 ***           iltr.DelayClearFlag                                    
 *** CFaltFilt
 *** r6        LostComnFaltBus/FaltBus/FaltFiltr3/FaltFiltrChrt.FaltF
 ***           iltr.DelaySetFlag                                      
 *** CFaltFilt
 *** r7        LostComnFaltBus/FaltBus/FaltFiltr3/FaltFiltrChrt.FaltF
 ***           iltr.FlagSet                                           
 *** CFaltFilt
 *** r1        LostComnFaltBus/FaltBus/FaltFiltr4/FaltFiltrChrt       
 *** CFaltFilt
 *** r2        LostComnFaltBus/FaltBus/FaltFiltr4/FaltFiltrChrt.Versi
 ***           onNumber                                               
 *** CFaltFilt
 *** r3        LostComnFaltBus/FaltBus/FaltFiltr4/FaltFiltrChrt.FaltF
 ***           iltr                                                   
 *** CFaltFilt
 *** r4        LostComnFaltBus/FaltBus/FaltFiltr4/FaltFiltrChrt.FaltF
 ***           iltr.FlagCleared                                       
 *** CFaltFilt
 *** r5        LostComnFaltBus/FaltBus/FaltFiltr4/FaltFiltrChrt.FaltF
 ***           iltr.DelayClearFlag                                    
 *** CFaltFilt
 *** r6        LostComnFaltBus/FaltBus/FaltFiltr4/FaltFiltrChrt.FaltF
 ***           iltr.DelaySetFlag                                      
 *** CFaltFilt
 *** r7        LostComnFaltBus/FaltBus/FaltFiltr4/FaltFiltrChrt.FaltF
 ***           iltr.FlagSet                                           
 *** CFaltFilt
 *** r1        LostComnFaltBus/FaltBus/FaltFiltr5/FaltFiltrChrt       
 *** CFaltFilt
 *** r2        LostComnFaltBus/FaltBus/FaltFiltr5/FaltFiltrChrt.Versi
 ***           onNumber                                               
 *** CFaltFilt
 *** r3        LostComnFaltBus/FaltBus/FaltFiltr5/FaltFiltrChrt.FaltF
 ***           iltr                                                   
 *** CFaltFilt
 *** r4        LostComnFaltBus/FaltBus/FaltFiltr5/FaltFiltrChrt.FaltF
 ***           iltr.FlagCleared                                       
 *** CFaltFilt
 *** r5        LostComnFaltBus/FaltBus/FaltFiltr5/FaltFiltrChrt.FaltF
 ***           iltr.DelayClearFlag                                    
 *** CFaltFilt
 *** r6        LostComnFaltBus/FaltBus/FaltFiltr5/FaltFiltrChrt.FaltF
 ***           iltr.DelaySetFlag                                      
 *** CFaltFilt
 *** r7        LostComnFaltBus/FaltBus/FaltFiltr5/FaltFiltrChrt.FaltF
 ***           iltr.FlagSet                                           
 *** CFaltFilt
 *** r1        LostComnFaltBus/FaltBus/FaltFiltr6/FaltFiltrChrt       
 *** CFaltFilt
 *** r2        LostComnFaltBus/FaltBus/FaltFiltr6/FaltFiltrChrt.Versi
 ***           onNumber                                               
 *** CFaltFilt
 *** r3        LostComnFaltBus/FaltBus/FaltFiltr6/FaltFiltrChrt.FaltF
 ***           iltr                                                   
 *** CFaltFilt
 *** r4        LostComnFaltBus/FaltBus/FaltFiltr6/FaltFiltrChrt.FaltF
 ***           iltr.FlagCleared                                       
 *** CFaltFilt
 *** r5        LostComnFaltBus/FaltBus/FaltFiltr6/FaltFiltrChrt.FaltF
 ***           iltr.DelayClearFlag                                    
 *** CFaltFilt
 *** r6        LostComnFaltBus/FaltBus/FaltFiltr6/FaltFiltrChrt.FaltF
 ***           iltr.DelaySetFlag                                      
 *** CFaltFilt
 *** r7        LostComnFaltBus/FaltBus/FaltFiltr6/FaltFiltrChrt.FaltF
 ***           iltr.FlagSet                                           
 *** CFaltDBGL
 *** og1       LostComnFaltBus/FaltDBGLogic/FaltLogLogic/FaltLogLogic 
 *** CFaltDBGL
 *** og2       LostComnFaltBus/FaltDBGLogic/FaltLogLogic/FaltLogLogic
 ***           .Faltchecking                                          
 *** 
 *** TargetLink version      : 2.3 from 05-Mar-2008
 *** Code generator version  : Build Id 2.3.0.17 from 2008-02-07 15:20:42
 *** Copyright (c) 2006 dSPACE GmbH
\**************************************************************************************************/

#ifndef _LOSTCOMNFALTBUS_CAL_C_
#define _LOSTCOMNFALTBUS_CAL_C_

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/
#include "lostcomnfaltbus_cal.h"
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/

#pragma section const_type ".FLASH_CAL_DATA" ".FLASH_CAL_DATA"
/******************************************************************************\
   CAL: global calibratable parameters (ROM) | Width: 16
\******************************************************************************/

__declspec (section ".FLASH_CAL_DATA") 
CAL U16 C_FaultTimeTrBO = 500 /* 50. */ /* LSB: 0.1 OFF:  0 MIN/MAX:  0 .. 6553.5 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U16 C_FaultTimeTrCH = 500 /* 50. */ /* LSB: 0.1 OFF:  0 MIN/MAX:  0 .. 6553.5 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U16 C_FaultTimeTrCO = 500 /* 50. */ /* LSB: 0.1 OFF:  0 MIN/MAX:  0 .. 6553.5 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U16 C_FaultTimeTrFR = 500 /* 50. */ /* LSB: 0.1 OFF:  0 MIN/MAX:  0 .. 6553.5 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U16 C_FaultTimeTrHY = 500 /* 50. */ /* LSB: 0.1 OFF:  0 MIN/MAX:  0 .. 6553.5 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U16 C_FaultTimeTrPMZ = 500 /* 50. */ /* LSB: 0.1 OFF:  0 MIN/MAX:  0 .. 6553.5 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U16 C_FaultTimeTrPT = 500 /* 50. */ /* LSB: 0.1 OFF:  0 MIN/MAX:  0 .. 6553.5 */;

#pragma section ".default"

/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INLINE FUNCTIONS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/

#endif/*_LOSTCOMNFALTBUS_CAL_C_ */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
