/**************************************************************************************************\
 *** 
 *** Simulink model       : Trjdc_Params_1_TL
 *** TargetLink subsystem : Trjdc_Params_1_TL/Trjdc_Params_1_TL/Subsystem/Trjdc_Params_1_TL/TrJdc_Pa
 ***                        rams
 *** Codefile             : trjdc_params_cal.c
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2018-02-06 12:05:46
 ***
 *** CODE GENERATOR OPTIONS:
 *** Compiler                            : <unknown>
 *** Target                              : Generic
 *** ANSI-C compatible code              : yes
 *** Optimization level                  : 2
 *** Constant style                      : decimal
 *** Clean code option                   : enabled
 *** Logging mode                        : Do not log anything
 *** Linker sections                     : enabled
 *** Assembler statements                : disabled
 *** Variable name length                : 31 chars
 *** Use global bitfields                : disabled
 *** Stateflow: use of bitfields         : enabled
 *** State activity encoding limit       : 5
 *** Omit zero inits in restart function : enabled
 *** Share fcns between TL subsystems    : disabled
 *** Generate 64bit functions            : disabled
 *** Inlining Threshold                  : 6
 *** Line break limit                    : 100
 *** Target optimized boolean data type  : enabled
 *** Keep saturation elements            : disabled
 *** Extended variable sharing           : disabled
 *** Style definition file               : C:\dSPACE\Matlab\Tl\config\codegen\cconfig.xml
 *** Root style sheet                    : C:\dSPACE\Matlab\Tl\XML\CodeGen\Stylesheets\TL_CSourceCod
 ***                                       eSS.xsl
 *** Enable Multirate codegeneration     : disabled
 *** Add model checksum                  : disabled
 ***
 *** SUBSYS                   CORRESPONDING SIMULINK SUBSYSTEM
 *** STrJdc_Para1             Trjdc_Params_1_TL/TrJdc_Params
 *** STrJdc_Para2             TrJdc_Params/Subsystem1
 *** STrJdc_Para3             TrJdc_Params/Subsystem2
 *** 
 *** SF-NODE   CORRESPONDING STATEFLOW NODE                           DESCRIPTION
 *** 
 *** TargetLink version      : 2.3 from 05-Mar-2008
 *** Code generator version  : Build Id 2.3.0.17 from 2008-02-07 15:20:42
 *** Copyright (c) 2006 dSPACE GmbH
\**************************************************************************************************/

#ifndef _TRJDC_PARAMS_CAL_C_
#define _TRJDC_PARAMS_CAL_C_

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/
#include "trjdc_params_cal.h"
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/

#pragma section const_type ".FLASH_CAL_DATA" ".FLASH_CAL_DATA"
/******************************************************************************\
   CAL: global calibratable parameters (ROM) | Width: 32
\******************************************************************************/

__declspec (section ".FLASH_CAL_DATA") 
CAL U32 LatchTimr_T = 120000 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 4294967295 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U32 fault_clear_time = 5000 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 4294967295 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U32 fault_heal_time = 60000 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 4294967295 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U32 ignition_timeout_cnt = 0 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 4294967295 */;

/******************************************************************************\
   CAL: global calibratable parameters (ROM) | Width: 16
\******************************************************************************/

__declspec (section ".FLASH_CAL_DATA") 
CAL U16 AutoTrChosn_T_Pt = 0 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U16 BldeDirctModeSelTimr_T_Dis_Pt = 30 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U16 LoPwModeDrvModeMsgReqActv_Z_Pt = 259 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U16 LoPwModeDrvModeMsgReqOff_Z_Pt = 0 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U16 LoPwModeDrvModeMsgReqSel_Z_Pt = 275 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U16 LoPwModeDrvModeMsgReqTrOff_Z_Pt = 178 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U16 LoPwModeMsgDsplyTimr_T_Pt = 5000 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U16 MskMissSigAirSusp_Z_Pt = 32 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U16 SpeclProgOff_T_Allw_Pt = 500 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U16 TrAutoButtnStatsValid_T_Pt = 0 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U16 available_time = 500 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U16 blink_time = 250 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U16 choosing_msg_time = 2000 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U16 chosen_time = 0 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U16 defaulting_msg_hold_time = 2000 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U16 fault_det_time = 250 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U16 ign_off_det_time = 300 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U16 ignition_timeout = 0 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U16 initial_msg_hold_time = 2000 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U16 mode_change_timeout = 1000 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U16 msg_hold_time = 5000 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U16 msg_visible_time = 200 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U16 not_available_timeout = 60000 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U16 road_chosen_time = 0 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U16 rot_pause_time = 500 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U16 selected_time = 0 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U16 sw_stuck_time = 2000 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;

/******************************************************************************\
   CAL: global calibratable parameters (ROM) | Width: 8
\******************************************************************************/

__declspec (section ".FLASH_CAL_DATA") 
CAL Bool AdvicSuspHi_B_Enbl_Pt = 0 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL Bool AirSuspSysPrtcp_B_Pt = 1 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL Bool ArcPrtcp_B_Pt = 0 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U8 BldeIntfcDirctActvBaseMsg_Z_Pt = 128 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL Bool BldeUseIntfc_B_Pt = 1 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U8 CONFIG_A_AV_REQD_BYTE = 6 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U8 CONFIG_A_NOT_FITTED_BYTE = 0 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U8 EcnmyButtnFaltMsk_Z_Pt = 64 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL Bool EcnmyModeTout_B_Pt = 1 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U8 FAULT_MSG = 150 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U8 HiUBattSocThres_Z_Pt = 0 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL Bool HndlConfgUseIntfc_B_Enbl_Pt = 0 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL Bool Jdc_B_Fit_Pt = 0 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U8 LedSwtchFaltMsk_Z_Pt = 16 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL Bool LoPwModeApplEnbl_B_Pt = 0 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U8 LoPwModeTerrModeReqOn_Z_Pt = 11 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U8 LoRngeMsk_Z_Pt = 32 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL Bool MedFricModeTout_B_Pt = 1 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U8 MedFricMode_Z_Pt = 10 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U8 Mode1Down_Pt = 6 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U8 Mode1Up_Pt = 1 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U8 Mode2Up_Pt = 4 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U8 Mode3Up_Pt = 3 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U8 Mode4Up_Pt = 5 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U8 Mode5Up_Pt = 12 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U8 ModeMsk_Z_Pt = 15 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U8 MskAirSuspAvail_Z_Pt = 128 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U8 NUMBER_OF_DTCS = 15 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U8 NumMode_Z_Pt = 4 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U8 PERFORM = 6 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U8 PERFORM_MSG = 6 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL Bool PREVIEW_OPTION = 1 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U8 ROCK_OPTION = 1 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U8 STATIONARY_MSG = 0 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL Bool SandModeTout_B_Pt = 1 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U8 TrApplVarnt_Pt = 4 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U8 TrJdcParamCol_Z_Pt = 11 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL Bool mode_air_av_reqd_b = 1 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL Bool mode_dlct_av_reqd_b = 1 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL Bool mode_ecm_av_reqd_b = 0 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL Bool mode_ems_av_reqd_b = 1 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL Bool mode_scs_av_reqd_b = 1 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL Bool mode_steer_av_reqd_b = 0 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL Bool mode_tcm_av_reqd_b = 0 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL Bool mode_tcu_av_reqd_b = 0 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL Bool rock_low_range_reqd_b = 1 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U8 sys_mode_av_reqd = 0 /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;

__declspec (section ".FLASH_CAL_DATA") 
CAL U8 SYS_INITIALISING[8] = {8,8,8,8,8,8,8,8}; /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
// Added manually and Call sheet modified for tool testing purpose
 
__declspec (section ".FLASH_CAL_DATA") 
CAL U8 SYS_FOLLOWING[8] = 
{8,8,8,8,8,8,8,8}; /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
// Added manually and Call sheet modified for tool testing purpose 
#pragma section ".default"

/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INLINE FUNCTIONS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/

#endif/*_TRJDC_PARAMS_CAL_C_ */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
